help:
	@echo
	@echo "You are looking at the project for RSSHit.com"
	@echo
	@echo "Make targets:"
	@grep '^[^	 ]*:' Makefile | sed 's/^/    /' | sed 's/://'
	@echo

newissue:
	open https://github.com/sordina/RSSHit/issues/new
